services:
  - type: web
    name: jobtrackr-api
    runtime: docker
    region: frankfurt
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    autoDeployTrigger: checksPass
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_TTL
        value: PT12H
      - key: REFRESH_TTL
        value: P30D
      - key: CORS_ALLOWED_ORIGINS
        value: https://trackmyjob-zakaria.netlify.app
